#deployment to AKS1
name: deploy-aks
on: [push]
env:
  REGISTRY_NAME: mmmazurepetstorecr
  CLUSTER_NAME: mmm-petstore-aks
  CLUSTER_RESOURCE_GROUP: dnd-petstore-rg
  NAMESPACE: dev-petstore
  SECRET: petstore-aks-secret
 

jobs:
  deploy-aks:
    runs-on: ubuntu-latest

    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2

      
      - uses: azure/setup-kubectl@v2.0

      # - name: Set the target AKS cluster
      #   uses: Azure/aks-set-context@v1
      #   with:
      #     creds: "${{ secrets.AZURE_CREDENTIALS }}"
      #     cluster-name: ${{ env.CLUSTER_NAME }}
      #     resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      
      # - name: Create namespace if doesn't exist
      #   run: |
      #     kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -
      
      # - name: Create image pull secret for ACR
      #   uses: Azure/k8s-create-secret@v1.1
      #   with:
      #     container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
      #     container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
      #     container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #     namespace: ${{ env.NAMESPACE }}
      #     secret-name: ${{ env.SECRET }}

      # - name: Deploy to AKS
      #   uses: Azure/k8s-deploy@v1
      #   with:          
      #     manifests: |
      #       deployments/master/aks-petstoreorderservice.yml
      #       deployments/master/aks-petstorepetservice.yml
      #       deployments/master/aks-petstoreproductservice.yml
      #       deployments/master/node-istio.yml
      #     imagepullsecrets: |
      #       ${{ env.SECRET }}
      #     namespace: ${{ env.NAMESPACE }}

      # # - name: Check deployment status 
      # #   run: |
      # #     kubectl get deployments -n ${{ env.NAMESPACE }}
      # #     kubectl get svc -n ${{ env.NAMESPACE }}
      # #     kubectl get vs -n ${{ env.NAMESPACE }}
      
     



      

